### PR TITLE
set up truffle and compiled contract

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Migration to local dev ganache 
- installed ganache 
- installed truffle and pet-box
- shifted the contract `Election.sol` & compiled successfully

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@narayanshivansh49 did this for now. Please review and merge 👍

**Comment by shivansh-narayan** [comment]
@ankingcodes seems that NJACK people have forgot to give write access to me
I have told them you can also do the same

**Comment by ankushbhardwxj** [comment]
@narayanshivansh49 okay !

**Comment by ankushbhardwxj** [comment]
I informed on the gitter channel

**Pull request merged**
